import type { Metadata } from "next";
import { Albert_Sans, Jost } from "next/font/google";
import "@/app/styles/scss/main.scss";

const albertSans = Albert_Sans({
   variable: "--font-albert-sans",
   subsets: ["latin"],
});

const jost = Jost({
   variable: "--font-jost",
   subsets: ["latin"],
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={`${albertSans.variable} ${jost.variable}`}>
            {children}
         </body>
      </html>
   );
}
